### ISSUE TITLE
ai-society

### ISSUE THREAD

**Issue by scgakki** [ah-ren/temp-files#3]
以制造业为例，当前的制造业不论是生产、流通还是销售，都正趋于数据化、智能化。大数据和人工智能技术可以协助企业分析生产过程中的全链路数据，实现生产效率、库存周转率、设备使用效率提升等目标。在智能制造进程中，工业机器人成为人工智能的典型代表，成为智能制造的重要实现端之一。

**Comment by Aoi-hosizora** [comment]
工业经济数字化、网络化、智能化发展成为第四次工业革命的核心内容，人工智能作为第四次工业革命的必然结果，在制造行业得到了很多应用，如……。

**Comment by Aoi-hosizora** [comment]
[可行性研究报告模板.docx](https://github.com/ah-ren/temp-files/files/7047065/default.docx)

.
